# Generated by Django 2.2.26 on 2022-03-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testapps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testapps',
            name='newtest',
        ),
        migrations.AddField(
            model_name='testapps',
            name='newtestss',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='testapps',
            name='oktested',
            field=models.TextField(blank=True),
        ),
    ]
